.gitignore, imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_xcorr.py, imod/viewers.py
Pull request for the construction of fiducial models based on the IMOD procedure.
DISCLAIMER: from now, in order to work with this protocol it is needed:
- fi_feature_fiducialModel branch in scipion-em-tomo package
- The needed changes in the init file of imod plugin to link the fiducial model generation protocol
- The wraper for the imod fiducial model generation protocol
- Some fixes in the xcorr alignment protocol
- The addition of summary and methods in the xcorr alignment protocol
- The changes needed in the imod viewer to be able to display fiducial models
=> Fi feature imod fid model

imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_newstack.py, imod/protocols/protocol_tomoReconstruction.py, imod/protocols/protocol_xcorr.py, imod/utils.py, imod/viewers.py
Pull request for the tomogram reconstruction and tilt-series interpolation protocols.
DISCLAIMER: from now, in order to work with this protocol it is needed:
- fi_feature_fiducialModel branch in scipion-em-tomo package
- New package utils with a common toolbox useful for several protocols for the plugin. This includes the pertinent changes in other protocols
- New protocol newstack for transformation matrix interpolation
- New protocol for tomogram reconstruction
- Changes in protocols.conf for easy access from Scipion tomography menu
- Changes in init protocol for tomogram reconstructions and apply transform protocols.\
- Changes in xcorr model protocol for iterative tilt series processing and streaming output
- Changes in fiducial model protocol including …
=> Fi feature tomo reconstruction

imod/protocols/__init__.py, imod/protocols/protocol_tsNormalization.py
Pull request for the construction of fiducial models based on the IMOD procedure.
- Changes in init to link the tilt-series normalization protocol
- The new tilt-series normalization protocol
=> Fi feature t snormalization

imod/protocols/protocol_tomoNormalization.py
Pull request with fixes in tomogram normalization protocol.
- Fixes in tomogram normalization protocol. Now properly applying binning factor using binvol  IMOD program
=> fixes in bining factor, now using binvol program

imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_tomoReconstruction.py, imod/viewers.py
- Changes in fiducial model protocol: improve readability
- Changes in fiducial model protocol: typo fixes
- Changes in fiducial model protocol: viewer fixes
- Changes in tomo reconstruction: new parameters
- Change in viewers: typo fixes
- Change in viewers: fiducial model viewer fixes
=> Fi fixes ts format

imod/protocols/__init__.py, imod/protocols/protocol_ctfCorrecion.py, imod/protocols/protocol_ctfEstimation.py, imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_tomoReconstruction.py, imod/viewers.py
- New protocol for CTF estimation
- New protocol for CTF correction
- Changes in init needed for new protcols
- Changes in fiducial model protocol: improve readability
- Changes in fiducial model protocol: typo fixes
- Changes in fiducial model protocol: fixes needed for viewer
- Changes in tomo reconstruction: new parameters
- Change in viewers: typo fixes
- Change in viewers: fiducial model viewer fixes
=> IMOD CTF + fixes and typos

imod/protocols/protocol_tomoNormalization.py
- Changes to optimize tomo normalization protocol in case only binning is needed
=> volume binning optimization

imod/__init__.py, imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_applyTransformationMatrix.py, imod/protocols/protocol_ctfCorrecion.py, imod/protocols/protocol_ctfEstimation.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_tomoNormalization.py, imod/protocols/protocol_tomoReconstruction.py, imod/protocols/protocol_tsNormalization.py, imod/protocols/protocol_xCorrPrealignment.py, imod/utils.py, setup.py
- automatic installation
- protocols conf update
- changes in apply transform protocol
- fixes in ctf estimation protocol
- new parameters in ctf estimation protocol
- fixes  in ctf correction protocol
- changes in protocol for executing installed software
- add description in imod utils
- changing development status in setup
=> Python3 migration

imod/protocols/protocol_applyTransformationMatrix.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_tsNormalization.py, imod/protocols/protocol_xCorrPrealignment.py
-Fixes in apply transform, fiducial alignment, ts normalization, and xcorr prealignment protocols in the output dimensions of binned tilt series
=> fixes in output tilt series dimensions when binning

imod/__init__.py, setup.py
This adds the libJpeg62 to the installation.
=> add jpeg62 library to the installation.

imod/tests/__init__.py, imod/tests/test_protocols_imod.py
- Changes in test init to link new datasets
- Refactor in prealignment test
- New test for the following protocols in two different workflow test classes: fiducial alignment, ts normalization, apply transform, tomo reconstruction, tomo normalization, ctf estimation and ctf correction
=> Fi feature test

imod/__init__.py, imod/protocols/protocol_ctfCorrecion.py, imod/protocols/protocol_etomo.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_tomoNormalization.py, imod/protocols/protocol_tsNormalization.py, imod/protocols/protocol_xCorrPrealignment.py, imod/viewers.py
- fixes in etomo, ctf correction, tomo normalization, ts normalization, 3dmod viewer, 
- new options in xcorr alignment
=> Fi fixes etomo

imod/viewers.py
Tomo viewer --> Command wasn't being correctly builded, a space was missing
=> Jj fix tomo viewer

imod/tests/__init__.py, imod/tests/test_protocols_imod.py
- Fixes in datasets of CTF workflow test
=> fixes test dataset

imod/__init__.py
- Fixes in IMOD installation. Now installing for all Linux distributions (previously only ubuntu)
=> Fi fixes instalation

imod/tests/test_protocols_imod.py
- Small fixes in fiducial alignment test to add tolerance
=> add tolerance to fiducial alignemnt test

imod/protocols/protocol_ctfEstimation.py, imod/tests/test_protocols_imod.py
- New feature in CTF estimation to include only tilt-series with a CTF estimation associated
- Changes from PR #34
=> Fi feature ctfplotter

imod/protocols/protocol_ctfEstimation.py
Fix Continue in protocol for CTF estimation
=> Fix Continue in protocol for CTF estimation

imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_tomoProjection.py, imod/protocols/protocol_tsNormalization.py, imod/tests/test_protocols_imod.py
- New protocol to project a set of tomograms at given angles, producing a set of tilt series
- Needed changes in init and protocols.conf
- Associated test in TestImodReconstructionWorkflow
- Small fixes in tomo normalizations
- Previous tests improved and refactored
=> Fi feature project tomo

imod/protocols/protocol_ctfCorrecion.py, imod/protocols/protocol_ctfEstimation.py
-Changes in CTF correction protocol to allow GPU acceleration
=> Fi feature ctf gpu acceleration  

imod/protocols/protocol_tomoReconstruction.py
- Changes needed in tomogram reconstruction protocol to allow for GPU acceleration
- Remove deprecated code in tomogram reconstruction protocol
=> Fi feature reconstruction GPU acceleration

imod/protocols/protocol_etomo.py
- Small changes in etomo convert input step to fix a problem with file extension
=> fixes in etom convert input step extenson

imod/protocols/protocol_etomo.py
-Small changes to fix the behavior of etomo (removing input binning)
=> small fixes in etomo binning

imod/__init__.py
- Changes in init protocol to update the installation. Now installing 4.11.0 version
To test:
- Uninstall scipion-em-imod
- Install scipion-em-imod
- Run plugin tests
=> Fi feature installation update

imod/protocols/protocol_fiducialAlignment.py
- Changes in fiducial alignment to save the ta solution output log
=> output file crrectly generated

imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_goldBeadPicker3d.py, imod/utils.py
- New protocol to peak 3d gold beads
- Needed changes in protocols.conf
- Needed changes in init
- New method in utils to read the protocol's output file
=> Fi feature gold bead3 d

imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_goldBeadPicker3d.py
- New params for gold bead picker protocol
- Parallelization for gold bead picker protocol
=> Fi feature gold beads params

imod/protocols/__init__.py
=> small fix in init

imod/__init__.py, imod/constants.py, imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_applyTransformationMatrix.py, imod/protocols/protocol_ctfCorrecion.py, imod/protocols/protocol_ctfEstimation.py, imod/protocols/protocol_etomo.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_goldBeadEraser.py, imod/protocols/protocol_goldBeadPicker3d.py, imod/protocols/protocol_tomoNormalization.py, imod/protocols/protocol_tomoProjection.py, imod/protocols/protocol_tomoReconstruction.py, imod/protocols/protocol_tsNormalization.py, imod/protocols/protocol_xCorrPrealignment.py, imod/protocols/protocol_xRaysEraser.py, imod/tests/__init__.py, imod/tests/test_protocols_imod.py, imod/utils.py, imod/viewers.py
- New protocol to erase gold beads (UNUSED)
- Changes in fiducial alignment to add gold bead eraser
- Refactor in form and other small fixes in fiducial alignment
- Remove output fiducial model with gaps from fiducial alignment (UNUSED)
- Fix email in all protocols header description
=> Fi feature erase gold beads

imod/utils.py
- Fixes in utils (CTF estimation) considering a new format of defocus file.
=> Fi fixes ctf flag file

imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_importSetOfCTFTomoSeries.py
This PR includes
- New protocol to import IMOD CTF estimations
- Changes needed in init
- Changes needed in protocols conf
=> Fi feature import ctf

imod/protocols/protocol_importSetOfTM.py
- Fixes in import transformation matrix protocol
=> Fi fixes import tm

imod/protocols/protocol_ctfCorrection.py, imod/protocols/protocol_ctfEstimation.py, imod/protocols/protocol_tomoReconstruction.py, imod/protocols/protocol_xRaysEraser.py
- Improvements in protocol form readability in CTF estimation and correction, tomo reconstruction and c-ray eraser.
=> Fi fixes improve readibility

imod/protocols/protocol_etomo.py, imod/protocols/protocol_fiducialAlignment.py
- Fixes in fiducial alignment calculateRotationAngleFromTM method
- Fixes in etomo extension parsing files, copytomocoms imod program
- Optimization in etomo
=> Fixes in fidcucila alginemnt and etomo

imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_doseFilter.py, imod/utils.py
- New protocol for TS dose filtering
- New method in utils to generate dose info files
- Sorting of methods listed in init
- Needed changes in init and protocols.conf
=> Fi feature dose filter

imod/__init__.py
=> send master to devel

imod/__init__.py, imod/file_handlers.py, imod/viewers/viewers.py
This add Imod as a file handler for .ali, .rec, .st files, so in the file browser imod and be used to show the files.
=> File handler

imod/protocols/protocol_doseFilter.py, imod/protocols/protocol_tomoProjection.py, imod/utils.py
- Changes in tomo projection to fix copy info inconsistency
DISCLAIMER: this PR needs of some changes in scipion-em-tomo (jj_tsImort_fixes)
=> Fi fixes tomo proj

imod/protocols/protocol_base.py, imod/protocols/protocol_ctfEstimation_automatic.py
- Fixes in output generation of CTF Tomoo Series
- Add control code in output generation of CTF Tomoo Series
=> Fi fixes output ctf

imod/protocols.conf, imod/protocols/__init__.py, imod/protocols/protocol_base.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_importSetOfCTFTomoSeries.py, imod/tests/test_protocols_imod.py, imod/viewers/viewers.py, imod/viewers/views_tkinter_tree.py
- Separate fiducial alignment in two protocols: fiducial alignment and generate landmark models
- Needed changes in _init_ and protocols.conf for the new protocol
- Needed changes in test due to new workflow
- Update and complete viewers for LandmarkModels and SetOfLandmarkModelsObject
IMPORTANT: This PR need the previous approval of scipion-em/scipion-em-tomo#154
=> Fi feature refactor fid ali

imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_fiducialModel.py
=> Fi fixes dalton

imod/protocols/protocol_fiducialAlignment.py
- Fixes in fiducial alignment output generation
=> Fi fixes fid ali

imod/protocols/protocol_etomo.py, imod/protocols/protocol_fiducialAlignment.py
This PR includes fixes for the scipion workshop:
- Fixes in etomo: output generation and remove rotation angle
- Fixes in fiducial alignment: matrix composition
=> Fi fixes workshop

imod/tests/test_protocols_imod.py
- Update tests to new parameters
=> update test value

imod/viewers/viewers.py
Fixing the viewers when Analize_Result button is pressed
=> Fix imod viewers

imod/protocols/protocol_fiducialModel.py, imod/viewers/viewers.py
The PR includes:
- Fixes in fiducial alignment
- Fixes in CTF correction
- Fixes in landmark models viewer
- Fixes in fiducial model bead radius -> bead diameter
=> Workshop fixes

imod/protocols/protocol_etomo.py
- Fixes in eTomo interactive protocol, relaunching recovers previous execution.
=> fixes etomo relauching project

imod/protocols/protocol_importSetOfTM.py
* Updating the tilt angles from .tlt file
* Fixing an error closing the set
=> Updating the tilt angles from .tlt file

imod/protocols/protocol_base.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_goldBeadPicker3d.py, imod/protocols/protocol_tsNormalization.py, imod/protocols/protocol_xRaysEraser.py, imod/tests/test_protocols_imod.py
- Changes in protocol base, link generation is no longer needed.
- Adapt fiducial alignment, fiducial model, tilt-series normalization, and x-rays eraser to changes in protocol base
- Fixes in tests. All passing
=> Fix unnecesary link II

imod/protocols/protocol_fiducialAlignment.py
- Fixes in summary and methods in fiducial alignment
=> Fix landmark models and tilt-series matching II 

imod/protocols/protocol_importSetOfTM.py
-Fix import TM, now closes set.
=> close output step import tmW

imod/protocols/protocol_fiducialAlignment.py
- Add tomId to output fiducial coordinates
=> Add tomId to fiducial coordinates

imod/protocols/protocol_base.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_goldBeadPicker3d.py, imod/protocols/protocol_importSetOfTM.py
This requires PR in scipion-em-tomo to be merged
https://github.com/scipion-em/scipion-em-tomo/pull/213
=> Use new object for tilt series coordinates

imod/protocols/protocol_base.py, imod/protocols/protocol_goldBeadPicker3d.py
-revest changes: generate 3d coordinates for gold bead picker 3d
=> Use new titl series coordinates fixes

imod/protocols/protocol_fiducialAlignment.py
- fixes in output interpolated dimensions in fiducial alignment
=> fixes in output interpolated dimensions in fiducial alignment

imod/protocols/protocol_fiducialAlignment.py
=> fixes in fiducial alignment

imod/protocols/protocol_base.py, imod/protocols/protocol_fiducialAlignment.py
Fixes in tilt series coordinates object
=> Fixes in tilt series coordinates object

imod/protocols/protocol_fiducialAlignment.py, imod/utils.py
- Changes in utils and fiducial alignment to Convert 3d coordinates based in imod dimensions
=> Convert 3d coordinates based in imod dimensions

imod/protocols/protocol_etomo.py
* Registering the excluded views
* Removing excludeList parameter
=> * Registering the excluded views

imod/protocols/protocol_base.py, imod/protocols/protocol_ctfEstimation_automatic.py, imod/protocols/protocol_ctfEstimation_manual.py
this is my approach to avoid interpolations but still using the same code.
=> Do not interpolate ts

README.rst, imod/__init__.py
=> * Updating README.rst

CHANGES.txt, imod/__init__.py, imod/utils.py
=> fix xf file reading

imod/protocols/protocol_applyTransformationMatrix.py, imod/protocols/protocol_ctfCorrection.py, imod/protocols/protocol_doseFilter.py, imod/protocols/protocol_tomoNormalization.py, imod/protocols/protocol_tsNormalization.py, imod/protocols/protocol_xRaysEraser.py
=> clear odd/even for the outputs if not used

imod/protocols/protocol_tomoNormalization.py
=> Added possible outputs

imod/protocols/protocol_ctfEstimation_automatic.py
This PR makes ctf estimation protocol tolerant to errors.
=> make ctf auomatic estimation tolerant to errors

imod/protocols/protocol_ctfCorrection.py
This PR make CTF correction tolerant to errors
=> make ctf correction tolerant to errors

imod/protocols/protocol_tomoReconstruction.py
This PR make tomo reconstruction tolerant to errors
=> make tomo rec error tolerant

imod/protocols/protocol_applyTransformationMatrix.py, imod/protocols/protocol_tsNormalization.py
This PR makes apply transform and normalize TS error resilient.
=> Fi feature error tolerancy

imod/protocols/protocol_ctfCorrection.py
Before: The number of tilt series must be equal tothe number of ctfTomoSeries
With this PR: Only those tilt series that find a corresponding ctfTomoSeries are corrected
=> fixing CTF issue

CHANGES.txt, imod/__init__.py, requirements.txt, setup.py
=> 3.2.2:   - Add requirements

imod/protocols/protocol_fiducialAlignment.py
Use nan for those landmarks containing no residual information
=> Fi fid ali fix

imod/protocols/protocol_base.py, imod/protocols/protocol_ctfEstimation_manual.py, imod/protocols/protocol_etomo.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_goldBeadPicker3d.py, imod/protocols/protocol_importSetOfTM.py, imod/protocols/protocol_tomoReconstruction.py
I am moving execution mode to class level.
Tests passed.
=> Executionmode

imod/utils.py
Fix IMOD landmark viewer: 
- Protect against decimal values
- Landmark size in angstroms
=> Fix LM viewer

.github/workflows/publish_and_tag.yml, CHANGES.txt, imod/protocols/protocol_base.py, imod/protocols/protocol_base_ts_align.py, imod/protocols/protocol_batch_run_tomo.py, imod/protocols/protocol_fiducialAlignment.py, imod/protocols/protocol_fiducialModel.py, imod/protocols/protocol_tomoReconstruction.py, imod/tests/tests_imod.py
All the tests are passing and the streaming workfows working fine, so these changeset is expected to be part of the release PR that is in draft state right now.
=> Jj fix brt e v

CHANGES.txt, imod/__init__.py, imod/protocols/protocol_applyTransformationMatrix.py, imod/protocols/protocol_ctfCorrection.py, imod/protocols/protocol_doseFilter.py, imod/protocols/protocol_excludeViews.py, imod/protocols/protocol_fiducial_eraser.py, imod/protocols/protocol_tomoPreprocess.py, imod/protocols/protocol_tomoProjection.py, imod/protocols/protocol_tsPreprocess.py, imod/protocols/protocol_xRaysEraser.py, imod/tests/tests_imod.py
Some refactoring was also carried out.
=> Jj add apix to files header
