scipion-em/scipion-em-imod

- imod/protocols/protocol_applyTransformationMatrix.py
- imod/protocols/protocol_ctfCorrecion.py
- imod/protocols/protocol_ctfEstimation.py
- imod/protocols/protocol_etomo.py
- imod/protocols/protocol_fiducialAlignment.py
- imod/protocols/protocol_tomoReconstruction.py
- imod/protocols/protocol_tsNormalization.py
- imod/protocols/protocol_xCorrPrealignment.py
- imod/utils.py
- Output filename fixes in all protocols
- Sqlite properties fixes in all protocols that output a set of tilt-series
- Refactor in etomo, fiducial alignment, tomo reconstruction, and tilt-series normalization
- Fixes in output landmark models in fiducial alignment
- Fixes in output set properties in etomo 
- Fixes in formating fiducial list methods in utils
> Fi fixes output file name

- imod/protocols/protocol_ctfCorrecion.py
- imod/protocols/protocol_ctfEstimation.py
- imod/protocols/protocol_etomo.py
- imod/protocols/protocol_fiducialAlignment.py
- imod/protocols/protocol_tomoNormalization.py
- imod/protocols/protocol_tomoReconstruction.py
- imod/protocols/protocol_tsNormalization.py
- imod/protocols/protocol_xCorrPrealignment.py
- Fixes in output generation in ctfCorrection, ctfEstimation, fidAlignment, tomoNormalization, tomoReconstruction, tsNormalization, xCorrPrealignment protocols.
- Remove deprecated code in ctfEstimation, fidAlignment,  tomoNormalization, tomoReconstruction, tsNormalization, xCorrPrealignment protocols
- Fixes in exclude views in etomo protocol
> Fi fixes ouput stream

- imod/protocols/protocol_applyTransformationMatrix.py
- imod/protocols/protocol_ctfCorrecion.py
- imod/protocols/protocol_ctfEstimation.py
- imod/protocols/protocol_tomoNormalization.py
- imod/protocols/protocol_tomoProjection.py
- imod/protocols/protocol_tomoReconstruction.py
- imod/protocols/protocol_tsNormalization.py
- imod/protocols/protocol_xCorrPrealignment.py
This PR includes changes to set the stream state to closed in the following protocols:
- Tomo normalization
- Tomo reconstruction
- Tomo projection
- CTF estimation 
- CTF correction
- Tilt-series normalization
- Tilt-series prealignment
> Fi fixes close ouptut sets

- imod/tests/test_protocols_imod.py
- Comment deprecated test that fails since the OutputFiducialModelGaps is not being generated anymore
> comment deprecated test

- imod/protocols/protocol_applyTransformationMatrix.py
- imod/protocols/protocol_fiducialAlignment.py
- imod/utils.py
- New method in utils to calculate the average rotation angle for every tilt image in the series given their transformation matrices
- Fixes in output dimension in apply transformation protocol
- Fixes in output dimension in fiducial alignment protocol
-Optimization in fiducial alignment protocol: reduce ts.getFirstItem() calls.
> Fi fixes output dim apply tm

- imod/protocols/protocol_fiducialAlignment.py
- imod/protocols/protocol_fiducialModel.py
- Fixes in generate fiducial models and fiducial alignment protocols: index of tilt image in Scipion Landmark models files starting at 1.
> fixes in fiducial alignment index in scipion lm

- imod/protocols/protocol_fiducialAlignment.py
So far the protocol checks if Imod has produced an output file but it does not check if the file is empty. We have added this second check.
>  check if Imod out file *.xf is empty and report it

- imod/utils.py
- Fixes in calculate avg rotation angle when ti has no transform: return 0
> Fixes in calculate average roation angle

- CHANGES.txt
- README.rst
- imod/protocols/protocol_applyTransformationMatrix.py
- imod/protocols/protocol_base.py
- imod/protocols/protocol_ctfCorrection.py
- imod/protocols/protocol_ctfEstimation_automatic.py
- imod/protocols/protocol_ctfEstimation_manual.py
- imod/protocols/protocol_excludeViews.py
- imod/protocols/protocol_fiducialAlignment.py
- imod/protocols/protocol_goldBeadPicker3d.py
- Erase gold option now works for fid. alignment protocol (close #146 )
- fix wrong output file index numbers in the exclude views protocol, also do not copy objId
- fix rotation angle range for swapping x/y for newstack
- do not copy objId for apply TM protocol when excluding views
- fix output size in apply TM protocol
- add a warning for ctf corr. protocol if inputting ts with no alignment
- remove ts interpolation before estimating ctf
> more fixes

- CHANGES.txt
- imod/__init__.py
- imod/protocols/protocol_ctfCorrection.py
- imod/protocols/protocol_tomoReconstruction.py
- tomoWidth added to specify a width when reconstructing
- Shift in Z is registered in tomogram origin
NOTE: Branch name is not descriptive.
>   - Reconstruction:

- CHANGES.txt
- imod/__init__.py
THis is just to avoid a gap. Latest was 3.1.8
> fix version

- imod/protocols/protocol_tomoReconstruction.py
Hi,
I added the `-SuperSampleFactor` option to the IMOD tomo reconstruction protocol with a default value of 2. This option greatly mitigates interpolation artefacts in Fourier backprojection (see images below). If you want to keep the old behavior unchanged, feel free to set the default value to 1.
`-SuperSampleFactor 1` (old behavior):
`-SuperSampleFactor 2` (new behavior):
Best wishes,
Ricardo
> Added option -SuperSampleFactor to tomo reconstruction protocol (tilt)

- CHANGES.txt
- imod/__init__.py
- imod/protocols/protocol_base.py
After the recent refactoring of CTF import, the flag was not set in the output
> bugfix for import ctf, set missing defocus flag

- CHANGES.txt
- imod/protocols/protocol_tomoNormalization.py
- imod/protocols/protocol_tsNormalization.py
- tilt series normalization: defines possible outputs
- tomo preprocess: always outputs mrc file
CHANGES corrected
>   - Prevent viewers from locking the screen focus.

- imod/protocols/protocol_fiducialAlignment.py
Small fix in fiducial alignment. There is an error in the chin ID when generating the output LM model
> fix fiducial alignment: output LM generation

- CHANGES.txt
- imod/__init__.py
- imod/protocols/protocol_base.py
- imod/utils.py
- requirements.txt
In scipion-em-tomo version 3.7.0, the acquisition order has been added to the CTFTomo to provide a robust field to match between tilt-images and CTFTomo when they come from different places, such as in Reliontomo prepare or IMOD ctf correction. It opens a way to robustly deal with re-stacked files, excluded vies, etc.
> Jj add acq order 2 ctftomo

- imod/protocols/protocol_applyTransformationMatrix.py
I was surprised to see that the aligned (interpolated) tilt series had a hard edge in the zero-filled part, so I added the IMOD defaults of tapering and linear interpolation. Linear interpolation can be toggled on/off as an advanced parameter. See the newstack [man page](https://bio3d.colorado.edu/imod/doc/man/newstack.html) for pros and cons of linear interpolation versus bicubic.
> Added tapering by default and option for linear interpolation in apply transform protocol

- imod/protocols/protocol_tomoReconstruction.py
Fixed a bug that was preventing the tomoReconstruction protocol from working on odd/even tilt-series
> Protocol was looking for odd/even input stacks in extra, but they are in tmp

- imod/protocols/protocol_applyTransformationMatrix.py
- imod/protocols/protocol_base.py
- imod/protocols/protocol_ctfCorrection.py
- imod/protocols/protocol_doseFilter.py
- imod/protocols/protocol_fiducialAlignment.py
- imod/protocols/protocol_fiducialModel.py
- imod/protocols/protocol_goldBeadPicker3d.py
- imod/protocols/protocol_tomoPreprocess.py
- imod/protocols/protocol_tomoProjection.py
- imod/protocols/protocol_tomoReconstruction.py
- imod/protocols/protocol_tsPreprocess.py
- imod/protocols/protocol_xCorrPrealignment.py
- imod/protocols/protocol_xRaysEraser.py
- imod/tests/test_protocols_imod.py
Fixed the issue with extensions discussed on Discord.
TO DO: implement cleanup of backup files (with `.mrc~` extension), will open an issue for that.
> Fixed extensions in protocol_tomoReconstruction.py, only uses MRC_EXT now

- imod/protocols/protocol_etomo.py
Followed suggestion from @pconesa on Discord
> Fixed bug that prevented etomo from opening when TS had excluded views created with Tomo viewer subset

- CHANGES.txt
- imod/__init__.py
- imod/protocols/protocol_tomoReconstruction.py
Odd/even tilt mrc reconstructions go to tmp and after trimvol they are in extra as expected.
> close #271

- imod/protocols/protocol_etomo.py
File with orig suffix does not exist, thus the TS with alignment metadata is never created
> Checking for the correct original filename in etomo protocol
